Demo/Demo.PL/Controllers/RoleController.cs
using Demo.DAL.Entities.Identity;
using Demo.PL.ViewModels.Roles;
using Demo.PL.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class RoleController : Controller
    {
        #region Services
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, IWebHostEnvironment webHostEnvironment,UserManager<ApplicationUser>userManager)
        {
            _roleManager = roleManager;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }
        #endregion

        #region Index


        [HttpGet]
        public async Task<IActionResult> Index(string SearchValue)
        {
            // Users
            var rolesQuery = _roleManager.Roles.AsQueryable();
            if (!string.IsNullOrEmpty(SearchValue)) // SearchValue = mariam
            {
                rolesQuery = rolesQuery.Where(R => R.Name.ToLower().Contains(SearchValue.ToLower()));
            }

            var rolesList = await rolesQuery.Select(R => new RoleViewModel
            {
                Id = R.Id,
                Name = R.Name,
                
               
            }).ToListAsync();


            return View(rolesList);
        }
        #endregion


        #region Create

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                await _roleManager.CreateAsync(new IdentityRole
                {
                    Name = roleViewModel.Name
                });

                return View(nameof(Index));
            }

            return View(roleViewModel);
        }



        #endregion

        #region Details

        [HttpGet]

        public async Task<IActionResult> Details(string? id)
        {
            if (id is null)
            {
                return BadRequest(); //400
            }

            var role = await _roleManager.FindByIdAsync(id);

            if (role is null)
            {
                return NotFound();
            }

            var roleVM = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name,
            
            };

            return View(roleVM);
        }

        #endregion


        #region Edit


        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            if (id is null)
            {
                return BadRequest(); //400
            }

            var role = await _roleManager.FindByIdAsync(id);
            var users =  await _userManager.Users.ToListAsync();  

            if (role is null)
            {
                return NotFound(); //404

            }
            var roleVM = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name,
                Users = users.Select(user => new UserRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    IsSelected = _userManager.IsInRoleAsync(user, role.Name).Result

                }).ToList()
              
            };
            return View(roleVM);



        }




        [HttpPost]
        // Show the Edit From
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(string id, RoleViewModel roleVM)
        {
            if (!ModelState.IsValid)
            {
                return View(roleVM);
            }

            else
            {
                var message = string.Empty;

                try
                {
                    var role = await _roleManager.FindByIdAsync(id);
                    if (role is null)
                    {
                        return NotFound(); //404

                    }
                    role.Name = roleVM.Name;

                    var Result = await _roleManager.UpdateAsync(role);

                    foreach (var userRole in roleVM.Users)
                    {
                        var user = await _userManager.FindByIdAsync(userRole.UserId);
                        if (user is not null)
                        {
                            if (userRole.IsSelected && !(await _userManager.IsInRoleAsync(user, role.Name))) // Sa7
                                await _userManager.AddToRoleAsync(user, role.Name);
                            else if (!userRole.IsSelected && await _userManager.IsInRoleAsync(user, role.Name)) // Checkbox empty
                                await _userManager.RemoveFromRoleAsync(user, role.Name);
                        }
                    }



                    if (Result.Succeeded)
                    {
                        return View(nameof(Index));

                    }
                    else
                    {
                        message = "role cannot be Updated";
                        TempData["Message"] = message;
                        ModelState.AddModelError(string.Empty, message);
                    }
                    return View(nameof(Index));


                }
                catch (Exception ex)
                {

                    message = _webHostEnvironment.IsDevelopment() ? ex.Message : "role Cannot be updated";

                }
                return View(nameof(Index));


            }



        }


        #endregion


        #region Delete

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            if (id is null)
            {
                return BadRequest(); //400
            }

            var role = await _roleManager.FindByIdAsync(id);

            if (role is null)
            {
                return NotFound(); //404

            }
            var userVM = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name,
            
            };
            return View(userVM);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> ConfirmDelete(string id)
        {
            var message = string.Empty;

            try
            {
                var user = await _roleManager.FindByIdAsync(id);
                if (user is not null)
                {

                    await _roleManager.DeleteAsync(user);
                    return View(nameof(Index));


                }


            }
            catch (Exception ex)
            {

                message = _webHostEnvironment.IsDevelopment() ? ex.Message : "Error when deleting the role";

            }
            ModelState.AddModelError(string.Empty, message);
            return View(nameof(Index));



        }




        #endregion



    }
}

Demo/Demo.PL/Controllers/UserController.cs
using Demo.BLL.DTOs.Employees;
using Demo.DAL.Entities.Identity;
using Demo.PL.ViewModels.Employee;
using Demo.PL.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo.PL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        #region Services
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;


        public UserController(UserManager<ApplicationUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }
        #endregion

        #region Index

        [HttpGet]
        public async Task<IActionResult> Index(string SearchValue)
        {
            // Users
            var usersQuery = _userManager.Users.AsQueryable();
            if (!string.IsNullOrEmpty(SearchValue)) // SearchValue = mariam
            {
                usersQuery = usersQuery.Where(U => U.Email.ToLower().Contains(SearchValue.ToLower()));
            }

            var usersList = await usersQuery.Select(U => new UserViewModel
            {
                Id = U.Id,
                FName = U.FName,
                LName = U.LName,
                Email = U.Email
            }).ToListAsync();

            foreach (var user in usersList)
            {
                user.Roles = await _userManager.GetRolesAsync(await _userManager.FindByIdAsync(user.Id));
            }

            return View(usersList);
        }
        #endregion
        #region Details

        [HttpGet]

        public async Task<IActionResult> Details(string? id)
        {
            if (id is null)
            {
                return BadRequest(); //400
            }

            var user = await _userManager.FindByIdAsync(id);

            if(user is null)
            {
                return NotFound();
            }

            var userVM = new UserViewModel()
            {
                Id = user.Id,
                FName = user.FName,
                LName = user.LName,
                Email = user.Email,
                Roles = _userManager.GetRolesAsync(user).Result
            };

            return View(userVM);
        }

        #endregion


        #region Edit


        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            if (id is null)
            {
                return BadRequest(); //400
            }

            var user = await _userManager.FindByIdAsync(id);

            if (user is null)
            {
                return NotFound(); //404

            }
            var userVM = new UserViewModel()
            {
                Id = user.Id,
                FName = user.FName,
                LName = user.LName,
                Email = user.Email,
                Roles = _userManager.GetRolesAsync(user).Result
            };
            return View(userVM);



        }




        [HttpPost]
        // Show the Edit From
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(string id, UserViewModel userVM)
        {
            if (!ModelState.IsValid)
            {
                return View(userVM);
            }

            else
            {
                var message = string.Empty;

                try
                {
                    var user = await _userManager.FindByIdAsync(id);
                    if (user is null)
                    {
                        return NotFound(); //404

                    }
                    user.FName = userVM.FName;
                    user.LName = userVM.LName;  
                    user.Email = userVM.Email;

                    var Result = await _userManager.UpdateAsync(user);


                    if (Result.Succeeded)
                    {
                        return View(nameof(Index));

                    }
                    else
                    {
                        message = "user cannot be Updated";
                        TempData["Message"] = message;
                        ModelState.AddModelError(string.Empty, message);
                    }
                    return View(nameof(Index));


                }
                catch (Exception ex)
                {

                    message = _webHostEnvironment.IsDevelopment() ? ex.Message : "user Cannot be updated";

                }
                return View(nameof(Index));


            }



        }


        #endregion


        #region Delete

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            if (id is null)
            {
                return BadRequest(); //400
            }

            var user = await _userManager.FindByIdAsync(id);

            if (user is null)
            {
                return NotFound(); //404

            }
            var userVM = new UserViewModel()
            {
                Id = user.Id,
                FName = user.FName,
                LName = user.LName,
                Email = user.Email,
                Roles = _userManager.GetRolesAsync(user).Result
            };
            return View(userVM);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> ConfirmDelete(string id)
        {
            var message = string.Empty;

            try
            {
                var user = await _userManager.FindByIdAsync(id);
                if (user is not null)
                {

                    await _userManager.DeleteAsync(user);
                    return View(nameof(Index));


                }


            }
            catch (Exception ex)
            {

                message = _webHostEnvironment.IsDevelopment() ? ex.Message : "Error when deleting the user";

            }
            ModelState.AddModelError(string.Empty, message);
            return View(nameof(Index));



        }

       


        #endregion





    }
}

Demo/Demo.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>@ViewData["Title"]</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/authStyleSheet.css" rel = "stylesheet"></link>
	<!-- //Custom Theme files -->
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		@RenderBody();
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>

	 <script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("validationScripts", required: false)


</body>
</html>

Demo/Demo.PL/Views/Shared/_ButtonsPartial.cshtml
@model string

<td>
<a class ="btn btn-primary"  asp-action="Details" asp-route-Id="@Model"> 
<i Class="fas fa-eye"></i> Details
    </a>
</td>

<td>
    <a class ="btn btn-success" asp-action="Edit" asp-route-Id="@Model"> 
<i Class = "fas fa-edit"></i> Edit
    </a>
</td>

<td>
    @*  <a class ="btn btn-danger"  asp-action="Delete" asp-route-Id="@Model">
            <i Class = "fas fa-trash"></i> Delete
    </a> *@

    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
            <i Class = "fas fa-trash"></i> Delete
    </button>
</td>

Demo/Demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.PL.styles.css" asp-append-version="true" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" /></head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li> 

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>


                     <li class="nav-item ms-auto">
                        <a class="nav-link text-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                    </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("validationScripts", required: false)
    @* @RenderSection("validationScripts", required: false) *@
</body>
</html>